#!/usr/bin/env python3
"""db_export.py — export the LVS reference netlist from the LIVE P&R database.

WHY THIS FILE EXISTS
--------------------
The naive LVS is circular: extract a netlist from the GDS, compare it against a
netlist derived from that same GDS. It cannot fail on the class of error it is
meant to catch, because both inputs share a common ancestor in the artifact under
test. Its outcome is determined by construction.

The fix: derive the reference from the live place-and-route database BEFORE
stream-out, so that

    P&R database --db_export.py--> reference_from_db.v  ---+
                                                            +--> Netgen LVS
    P&R database --> GDS --> Magic extract --> layout.spice -+

are two INDEPENDENT derivations from one live database. Only then does the
comparison have diagnostic power.

This is a TEACHING implementation. It consumes a JSON dump of the P&R database:

    {
      "design": "my_first_gds",
      "instances": [
        {"name": "u1", "cell": "sky130_fd_sc_hd__inv_2",
         "ports": {"A": "n3", "Y": "n7", "VPWR": "VPWR", "VGND": "VGND"}},
        ...
      ],
      "ports": [{"name": "clk", "direction": "input", "net": "clk"}]
    }

Adapt the loader to your P&R tool; keep the two INVARIANTS below.

INVARIANTS (do not break these)
  I1  Deterministic: no dict/set iteration order leaks into the output, no
      timestamps, no absolute paths. Run twice -> identical bytes.
  I2  Power/ground connectivity of decap and filler cells is taken from the
      AUTHORITATIVE PDK CDL/SPICE, not inferred from the layout. Pass it in with
      --pg if your dump omits it.

Usage
    python3 db_export.py --db-in layout.db.json \
                         --out   $RUN_DIR/reference_from_db.v \
                         --marker $RUN_DIR/.db_export_marker
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
from pathlib import Path

# Decap / filler cells: connect power and ground from the PDK, never from layout
# (review 03, rule G2). If the DB dump already carries VPWR/VGND pins, this map is
# only used to fill gaps — and every gap it fills is reported.
DEFAULT_PG = {
    "sky130_fd_sc_hd__decap_3": ("VPWR", "VGND"),
    "sky130_fd_sc_hd__decap_4": ("VPWR", "VGND"),
    "sky130_fd_sc_hd__decap_6": ("VPWR", "VGND"),
    "sky130_fd_sc_hd__decap_8": ("VPWR", "VGND"),
    "sky130_fd_sc_hd__fill_1": ("VPWR", "VGND"),
    "sky130_fd_sc_hd__fill_2": ("VPWR", "VGND"),
    "sky130_fd_sc_hd__fill_4": ("VPWR", "VGND"),
    "sky130_fd_sc_hd__fill_8": ("VPWR", "VGND"),
}

SUPPLY_NETS = ("VPWR", "VGND", "VDD", "VSS", "VPB", "VNB")


def die(msg: str, code: int = 2) -> "NoReturn":  # type: ignore[valid-type]
    print(f"db_export: {msg}", file=sys.stderr)
    raise SystemExit(code)


def load_db(path: Path) -> dict:
    try:
        db = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        die(f"database dump not found: {path}")
    except json.JSONDecodeError as exc:
        die(f"database dump is not valid JSON: {exc}")
    for key in ("design", "instances"):
        if key not in db:
            die(f"database dump is missing required key '{key}'")
    return db


def emit_verilog(db: dict, pg_map: dict) -> tuple[str, list[str]]:
    """Return (verilog_text, notes). Sorted everywhere: invariant I1."""
    design = db["design"]
    instances = sorted(db["instances"], key=lambda i: i["name"])
    ports = sorted(db.get("ports", []), key=lambda p: p["name"])

    if ports:
        port_names = [p["name"] for p in ports]
    else:
        # Fall back to top-level nets that are not purely internal.
        port_names = sorted({p for i in instances for p in i.get("ports", {})})

    lines: list[str] = []
    lines.append("// GENERATED by db_export.py — LVS reference source.")
    lines.append("// Derived from the LIVE place-and-route database, BEFORE GDS stream-out.")
    lines.append("// Do not edit by hand. Regenerate instead.")
    lines.append("// This file is one of two INDEPENDENT derivations fed to Netgen.")
    lines.append("")
    lines.append(f"module {design} (")
    for i, name in enumerate(port_names):
        sep = "," if i < len(port_names) - 1 else ""
        lines.append(f"    {name}{sep}")
    lines.append(");")
    lines.append("")

    # directions, if the dump carries them
    dirs = {p["name"]: p.get("direction") for p in ports}
    for kind in ("input", "output", "inout"):
        names = [n for n in port_names if dirs.get(n) == kind]
        if not names:
            continue
        width = "" if len(names) == 1 else f"[{len(names) - 1}:0] "
        if len(names) == 1:
            lines.append(f"    {kind} {names[0]};")
        else:
            lines.append(f"    {kind} {width}{', '.join(names)};")
    if any(dirs.values()):
        lines.append("")

    # wires: every net that is not a port and not a supply
    nets = set()
    for inst in instances:
        for net in inst.get("ports", {}).values():
            if net and net not in port_names and net not in SUPPLY_NETS:
                nets.add(net)
    for net in sorted(nets):
        lines.append(f"    wire {net};")
    if nets:
        lines.append("")

    notes: list[str] = []
    for inst in instances:
        cell = inst["cell"]
        pins = inst.get("ports", {})
        conns = []
        # sorted by pin name: invariant I1
        for pin in sorted(pins):
            net = pins[pin]
            if not net and cell in pg_map:
                vdd, gnd = pg_map[cell]
                net = vdd if pin.upper() in ("VPWR", "VDD", "VPB") else gnd
                notes.append(
                    f"{inst['name']}: pin {pin} empty -> "
                    f"filled from PDK pg-map as {net} (cell {cell})"
                )
            if net:
                conns.append(f".{pin}({net})")
        lines.append(f"    {cell} {inst['name']} ( {', '.join(conns)} );")

    lines.append("")
    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines), notes


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--db-in", required=True, type=Path, help="P&R database JSON dump")
    ap.add_argument("--out", required=True, type=Path, help="reference verilog to write")
    ap.add_argument("--marker", required=True, type=Path,
                    help="marker file proving the export ran pre-streamout")
    ap.add_argument("--pg", type=Path, default=None,
                    help="optional JSON map cell -> [power_net, ground_net]")
    args = ap.parse_args()

    db = load_db(args.db_in)

    pg_map = dict(DEFAULT_PG)
    if args.pg:
        try:
            extra = json.loads(args.pg.read_text(encoding="utf-8"))
        except (FileNotFoundError, json.JSONDecodeError) as exc:
            die(f"--pg file unreadable: {exc}")
        for cell, pair in extra.items():
            pg_map[cell] = tuple(pair)

    text, notes = emit_verilog(db, pg_map)

    # invariant I1: identical bytes on every run, for the same database.
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8", newline="\n")

    # The marker is what run_all.sh checks. It records a fingerprint of the
    # DATABASE (not of any GDS) so the provenance of the reference is auditable.
    db_sha = hashlib.sha256(
        json.dumps(db, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()
    out_sha = hashlib.sha256(text.encode("utf-8")).hexdigest()
    args.marker.write_text(
        "db_export.py marker\n"
        f"db_sha256    {db_sha}\n"
        f"ref_sha256   {out_sha}\n"
        f"exported_utc {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}\n"
        f"source       {args.db_in.name}\n"
        "stage        PRE-STREAMOUT\n",
        encoding="utf-8",
        newline="\n",
    )

    print(f"db_export: wrote {args.out}  (sha256 {out_sha[:16]}…)")
    print(f"db_export: marker {args.marker.name}  (db sha256 {db_sha[:16]}…)")
    for n in notes:
        print(f"db_export: note  {n}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
